Firts try, nothing tested

diff --git a/pkg/ubuntu/diaspora-wsd b/pkg/ubuntu/diaspora-wsd
--- a/pkg/ubuntu/diaspora-wsd
+++ b/pkg/ubuntu/diaspora-wsd
@@ -1,102 +1,150 @@
-#!/bin/bash
-#
-#	/etc/rc.d/init.d/diaspora-wsd
-#
-# SHOULD start the diaspora websocket daemon, but it doesn't. No way.
-#
-# chkconfig: - 80 80
-# description: Diaspora websocket daemon
-
+#! /bin/sh
 ### BEGIN INIT INFO
-# Provides: diaspora-wsd
-# Required-Start: $local_fs $network
-# Required-Stop: $local_fs $network
-# Should-Start: $remote_fs
-# Should-Stop: $remote_fs
-# Default-Start:
-# Default-Stop: 0 1 2 3 4 5 6
-# Short-Description: start and stop Diaspora websocket server
-# Description: The websocket server provides websocket services for
-#              diaspora.
+# Provides:          diaspora-wsd
+# Required-Start:    $remote_fs $syslog
+# Required-Stop:     $remote_fs $syslog
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: diaspora websocket daemon
+# Description:       The diaspora websocket service provider, normally
+                     listening on port 8080
 ### END INIT INFO
 
-# Source function library.
-. /etc/init.d/functions
+# Author: Alec leamas <leamas.alec@gmail.com>
 
-if [ -f /etc/sysconfig/diaspora-wsd -a $UID -eq 0 ]; then
-    . /etc/sysconfig/diaspora-wsd
-fi
+PATH=/usr/sbin:/usr/bin
+DESC="Websocket server for diaspora clients"
+NAME='diaspora-wsd'
+DAEMON='/usr/share/diaspora/master/script/websocket_server.rb'
+DAEMON_ARGS=""
+PIDFILE=/var/run/diaspora/diaspora-wsd.pid
+SCRIPTNAME=/etc/init.d/diaspora-wsd
 
-# Note: this line is patched by installation scripts.
-cd  /usr/share/diaspora
+[ -x "$DAEMON" ] || exit 0
+vncvi	
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
-RETVAL=0
-prog="Diaspora websocket server"
-exec="script/websocket_server.rb"
-pidfile="/var/run/diaspora-wsd"
-lockfile="/var/lock/subsys/diaspora-wsd"
-logfile=/var/log/diaspora-wsd.log
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
 
-[ -n "$OPTIONS" ] && OPTIONS=" $OPTIONS"
-ruby_cmd="ruby -C $PWD $exec$OPTIONS"
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
+. /lib/lsb/init-functions
 
-start() {
-	[ $UID -eq 0 ] || exit 4
-	[ -f $exec ]   || exit 5
-
-        echo -n $"Starting $prog: "
-	daemon --pidfile $pidfile "$ruby_cmd >>$logfile 2>&1 &"
-	RETVAL=$?
-        echo
-	if test $RETVAL = 0; then
-            touch  $lockfile
-            pgrep -f "$ruby_cmd" > $pidfile || {
-                echo "Warning: cannot find running diaspora-webserver"
-                exit 7
-            }
-        fi
-}
-
-stop() {
-	[ $UID -eq 0 ] || exit 4
-	echo -n $"Stopping $prog: "
-	killproc -p $pidfile $exec
-	RETVAL=$?
-	[ $RETVAL -eq 0 ] && rm -f $lockfile
-	echo
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+		|| return 1
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
+		$DAEMON_ARGS \
+		|| return 2
+	# Add code here, if necessary, that waits for the process to be ready
+	# to handle requests from services started subsequently which depend
+	# on this one.  As a last resort, sleep for some time.
 }
 
 #
-#	See how we were called.
+# Function that stops the daemon/service
 #
+do_stop()
+{
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+	RETVAL="$?"
+	[ "$RETVAL" = 2 ] && return 2
+	# Wait for children to finish too if this is a daemon that forks
+	# and if the daemon is only ever run from this initscript.
+	# If the above conditions are not satisfied then add some other code
+	# that waits for the process to drop all resources that could be
+	# needed by services started subsequently.  A last resort is to
+	# sleep for some time.
+	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+	[ "$?" = 2 ] && return 2
+	# Many daemons don't delete their pidfiles when they exit.
+	rm -f $PIDFILE
+	return "$RETVAL"
+}
+
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload() {
+	#
+	# If the daemon can reload its configuration without
+	# restarting (for example, when it is sent a SIGHUP),
+	# then implement that here.
+	#
+	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
+	return 0
+}
+
 case "$1" in
   start)
-	start
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	do_start
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
 	;;
   stop)
-	stop
-	;;
-  force-reload|restart)
-	stop
-	sleep 1
-	start
-	RETVAL=$?
-	;;
-  condrestart|try-restart)
-	if [ -f $lockfile ]; then
-	    stop
-	    sleep 3
-	    start
-	fi
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	do_stop
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
 	;;
   status)
-	status -p $pidfile $exec
-	RETVAL=$?
+       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+       ;;
+  #reload|force-reload)
+	#
+	# If do_reload() is not implemented then leave this commented out
+	# and leave 'force-reload' as an alias for 'restart'.
+	#
+	#log_daemon_msg "Reloading $DESC" "$NAME"
+	#do_reload
+	#log_end_msg $?
+	#;;
+  restart|force-reload)
+	#
+	# If the "reload" option is implemented then remove the
+	# 'force-reload' alias
+	#
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	  0|1)
+		do_start
+		case "$?" in
+			0) log_end_msg 0 ;;
+			1) log_end_msg 1 ;; # Old process is still running
+			*) log_end_msg 1 ;; # Failed to start
+		esac
+		;;
+	  *)
+	  	# Failed to stop
+		log_end_msg 1
+		;;
+	esac
 	;;
   *)
-	echo $"Usage: $0 {condrestart|try-restart|start|stop|restart|force-reload|status}"
-	RETVAL=2
-	[ "$1" = 'usage' ] && RETVAL=0
+	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
+	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+	exit 3
+	;;
 esac
 
-exit $RETVAL
+:
