Handle jammit by precaching in script/server.
This introduces some jammit warnings in 'rake spec'. These seem
to be just warnings. To get rid of them, take steps as described in
https://github.com/diaspora/diaspora/wiki/Installing-and-Running-Diaspora
in the "Read-only Installation" (sic!) chapter.

diff --git a/script/server b/script/server
--- a/script/server
+++ b/script/server
@@ -48,6 +48,16 @@ if [ ! -e public/source.tar.gz ]; then
     exit 65
 fi
 
+# Precache jammit assets
+if [ -w public ]; then
+    bundle exec jammit
+fi
+if [ ! -e 'public/assets/main.js.gz' ]; then
+    echo 'Jammit precache error (now or at install)' >&2
+    exit 66
+fi
+
+
 mkdir -p -v log/thin/
 bundle exec ruby ./script/websocket_server.rb&
 bundle exec magent start --log-path=log/ &
